info:
  component: Zuul Server
  
endpoints:
  enabled: false
  restart:
    enabled: false
  shutdown:
    enabled: false
  health:
    sensitive: false

ribbon:
  eureka:
     enabled: false

zuul:
  host:
    # this value need to be big enough because internal search interface sometimes is very slow.
    socket-timeout-millis: 10000
  routes:
    account:
      path: /**
      stripPrefix: false
      url: https://account-huami.mi-ae.cn:443

server:
  port: 8080
