info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

ribbon:
  eureka:
     enabled: false

zuul:
  host:
    socket-timeout-millis: 30000
  routes:
    server:
      path: /**
      stripPrefix: false
      url: https://account-huami.mi-ae.cn:443

server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
